config: !!python/object/apply:dotmap.DotMap
  dictitems:
    system: &id004 !!python/object/apply:dotmap.DotMap
      dictitems:
        data: &id001 !!python/object/apply:dotmap.DotMap
          dictitems:
            root: ./artifacts/data/mnist
          state:
            _dynamic: true
            _map: !!python/object/apply:collections.OrderedDict
            - - - root
                - ./artifacts/data/mnist
            _prevent_method_masking: false
        model: &id002 !!python/object/apply:dotmap.DotMap
          dictitems:
            name: linear
          state:
            _dynamic: true
            _map: !!python/object/apply:collections.OrderedDict
            - - - name
                - linear
            _prevent_method_masking: false
        optimizer: &id003 !!python/object/apply:dotmap.DotMap
          dictitems:
            batch_size: 32
            lr: 0.004
            max_epochs: 10
          state:
            _dynamic: true
            _map: !!python/object/apply:collections.OrderedDict
            - - - max_epochs
                - 10
              - - batch_size
                - 32
              - - lr
                - 0.004
            _prevent_method_masking: false
        save_dir: ./artifacts/ckpts/train_flow
      state:
        _dynamic: true
        _map: !!python/object/apply:collections.OrderedDict
        - - - data
            - *id001
          - - model
            - *id002
          - - optimizer
            - *id003
          - - save_dir
            - ./artifacts/ckpts/train_flow
        _prevent_method_masking: false
    wandb: &id005 !!python/object/apply:dotmap.DotMap
      dictitems:
        entity: emekdahl
        project: train_flow
      state:
        _dynamic: true
        _map: !!python/object/apply:collections.OrderedDict
        - - - project
            - train_flow
          - - entity
            - emekdahl
        _prevent_method_masking: false
  state:
    _dynamic: true
    _map: !!python/object/apply:collections.OrderedDict
    - - - system
        - *id004
      - - wandb
        - *id005
    _prevent_method_masking: false
